# Generated by Django 3.2.6 on 2022-03-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='imageofbrand',
            field=models.ImageField(default='asd', upload_to='images'),
            preserve_default=False,
        ),
    ]
