# Generated by Django 3.2.6 on 2022-03-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('testcase', models.TextField()),
                ('imageofproduct', models.ImageField(upload_to='stactic/img/')),
                ('brandSelection', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='seller.brand')),
                ('categorySelection', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
            ],
        ),
    ]
