# Generated by Django 3.2.6 on 2022-03-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='imageofproduct',
            field=models.ImageField(upload_to='images'),
        ),
    ]
