# Generated by Django 3.2.6 on 2022-03-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_creatinguser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatinguser',
            old_name='password',
            new_name='passWord',
        ),
    ]
